Updating documentation and input file using metal database
ReactionMechanismGenerator/RMG-Py pull request #2110
Opened 2021-04-20 18:26 UTC by mazeau

This PR updates the surface documentation with instructions on how to use the metal database to specify certain metals instead of having to manually enter in binding energies and surface site density.

I also changed the ch4_o2 example input file to call `Pt111` in place of listing out Pt111 binding energies and surface site density

2021-04-20 18:36 UTC, ChrisBNEU approved these changes
This looks fine to me.

2021-04-20 20:25 UTC, rwest requested changes
Thanks. Would be good to tell people where to find the list of available metals and facets. 
Also there's a typo (Rh instead of Pt).

2021-04-20 20:25 UTC, rwest commented on documentation/source/users/rmg/surfaces.rst
> +Here is an example catalyst properties block for Rh(111)::
```suggestion
Here is an example catalyst properties block for Pt(111)::
```

2021-04-21 17:01 UTC, davidfarinajr commented
Yep, looks good and I agree with Richard; we should tell people where to find available metals/facets in docs.  Perhaps we could have a `Metal Search` or something on the website so people can look it up and see what atomic binding energies would be used for metal of interest.

2021-04-21 17:45 UTC, mazeau commented
> Yep, looks good and I agree with Richard; we should tell people where to find available metals/facets in docs. Perhaps we could have a `Metal Search` or something on the website so people can look it up and see what atomic binding energies would be used for metal of interest.

I like the website idea! But I think that should be a separate PR. I somehow missed the part about telling people where to find the database, so I will add that in

2021-04-21 18:27 UTC, davidfarinajr approved these changes
Thanks @mazeu.  Looks good to me

2021-04-22 03:57 UTC, rwest approved these changes
Looks good now, and the example runs fine. Thanks.
I fixed some whitespace on rebasing, and will now merge

2021-04-22 03:58 UTC, merged