SurfaceArrhenius <=> StickingCoefficient
ReactionMechanismGenerator/RMG-Py pull request #2148
Opened 2021-05-31 16:56 UTC by davidfarinajr

### Motivation or Problem
Some surface reaction families have training data with mixed kinetics types (SurfaceArrhenius and StickingCoeff).  We need methods to convert SurfaceArrhenius to StickingCoeff and vice versa so that we can convert the training data to the same kinetics type so that we can average them.

### Description of Changes
- created methods to convert StickingCoeff to SurfaceArrhneius and SurfaceArrhenius to StickingCoeff
- if there is a stickingcoeff reaction in training data with Surface Arrhenius, convert Surface Arrh to Sticking Coefficient when adding the rules
- added a check to make sure that the kinetics types are all the same when averaging kinetics 

### Testing
- Built a model with the DB branch for this PR https://github.com/ReactionMechanismGenerator/RMG-database/pull/479, where we have mixed kinetics types in training
- tested the Surf Arrh <--> StickingCoeff method in Jupyter notebook, but have not added unit tests yet

2021-05-31 17:49 UTC, Tingchenlee commented
I also ran a test(which included `CH4`, `NH3`, and `O2`species) with all new libraries and surface families, and the model was completed.

2021-06-04 17:31 UTC, rwest commented
These are useful methods to have, to convert back and forth, and we should keep them, but I feel like training reactions should all be in the same format in the database, and the person adding them to the database should convert at that point, rather than when loading the database at run time.  This will greatly simplify the averaging, and the interpretation of averaging, and Matt's auto tree generation, etc.

So I suggest a unit test added to the database checks to ensure all training reactions in adsorption reaction families are in StickingCoefficient form (and perhaps prints the helpful conversion in the error report if it's in SurfaceArrhenius, to facilitate changing it).

2021-06-04 17:51 UTC, rwest commented
Worth checking we do this: things entered in the reverse direction (i.e. desorption) will be a `SurfaceArrhenius` with units of `1/s`. These will need converting into a `StickingCoefficient`, not just a reversed `SurfaceArrhenius`.

2021-06-24 18:13 UTC, mazeau requested changes
This looks good! I just am not a fan of the hard coded stuff

2021-06-24 18:13 UTC, mazeau commented on rmgpy/data/kinetics/family.py
> +                        surface_site_density = 2.483e-09
I think instead of having this hard coded in, you should load it from the metal database

2021-06-24 18:13 UTC, mazeau commented on rmgpy/data/kinetics/family.py
> +                        surface_site_density = 2.483e-09
here as well

2021-06-24 18:13 UTC, mazeau commented on rmgpy/data/kinetics/family.py
> +                        surface_site_density = 2.483e-09
don't remember what the units are in the db, so this might affect your reaction.py additions

2021-07-15 18:53 UTC, ChrisBNEU approved these changes
I left some nitpicky comments, but these two new functions are tools that are not used in the main RMG model building code, so I think it is good to go.

2021-07-15 18:53 UTC, ChrisBNEU commented on rmgpy/reaction.py
> +                    logging.error("Error in kinetics for reaction {0!s}: "
nitpicky, but do we have adsorption reactions that have multiple adsorbates? I think this is really testing if the reaction is the correct type (i.e. adsorption). maybe the text could say "multiple adsorbates detected, reaction probably isn't adsorption"?

2021-07-15 18:53 UTC, ChrisBNEU commented on rmgpy/reaction.py
> +        for i in range(number_of_sites):
nitpicky, but this could just be klist *= surface_site_density**number_of_sites.

2023-07-23 08:06 UTC, closed without merging