Fix RMS Object Construction
ReactionMechanismGenerator/RMG-Py pull request #2208
Opened 2021-10-05 15:41 UTC by mjohnson541

This fixes a few different bugs related to construction of RMS objects for more complex kinetics types particularly Multi/Pdep/Arrhenius and falloff types. 

Best test is to run RMG with libraries containing these kinetic types.

2021-10-06 15:55 UTC, mazeau reviewed
happy to approve! thanks so much, matt!

2021-10-06 17:20 UTC, davidfarinajr requested changes
Thanks for fixing this @mjohnson541 !  I found a couple of potential bugs in `add_reaction` Phase function (see comments).  Also, I am not 100% sure that species_names is in the same order as `rmg_species`, and I didn't follow the code all the way through to check, but it looks like they should be?

2021-10-06 17:20 UTC, davidfarinajr commented on rmgpy/rmg/reactors.py
> +        efficiencies = {species_names[i] : float(val) for i, val in enumerate(obj.get_effective_collider_efficiencies(rmg_species)) if val != 1}
Are we sure that `species_names` is in the same order as `rmg_species`?  For a phase, it seems like they should be, not sure if we are also using this for interphase.

2021-10-30 15:37 UTC, davidfarinajr approved these changes

2021-10-30 15:38 UTC, davidfarinajr commented
I just rebased and approved.  I'll merge it after the tests pass

2021-10-30 16:58 UTC, merged

2021-10-31 02:43 UTC, NUSCondy commented
Hi,
I have updated to this main version and try to run and encountered this:
**Traceback (most recent call last):
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhuqiren/RMG-Py/rmg.py", line 48, in <module>
    from rmgpy.rmg.main import RMG, initialize_log, process_profile_stats, make_profile_graph
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/main.py", line 55, in <module>
    from rmgpy.rmg.model import Species, CoreEdgeReactionModel
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 41, in <module>
    import rmgpy.data.rmg
  File "/home/zhuqiren/RMG-Py/rmgpy/data/rmg.py", line 38, in <module>
    from rmgpy.data.base import ForbiddenStructures
  File "/home/zhuqiren/RMG-Py/rmgpy/data/base.py", line 44, in <module>
    from rmgpy.kinetics.uncertainties import RateUncertainty
  File "/home/zhuqiren/RMG-Py/rmgpy/kinetics/__init__.py", line 30, in <module>
    from rmgpy.kinetics.model import KineticsModel, PDepKineticsModel, TunnelingModel, \
  File "__init__.pxd", line 918, in init rmgpy.kinetics.model
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject**

2021-10-31 03:43 UTC, davidfarinajr commented
@NUSCondy , this looks to me like a cython error.  Have you tried `make` , and if that doesn't work `make clean` and `make` in the rmgpy home folder?

2021-10-31 03:59 UTC, NUSCondy commented
Yes I have tried make clean and then make.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: davidfarinajr ***@***.***>
Sent: Sunday, October 31, 2021 11:44:01 AM
To: ReactionMechanismGenerator/RMG-Py ***@***.***>
Cc: Zhu Qiren ***@***.***>; Mention ***@***.***>
Subject: Re: [ReactionMechanismGenerator/RMG-Py] Fix RMS Object Construction (#2208)

        - External Email -



@NUSCondy<https://github.com/NUSCondy> , this looks to me like a cython error. Have you tried make , and if that doesn't work make clean and make in the rmgpy home folder?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2208#issuecomment-955631528>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOTBI6T75P3XSRRW4SKSOZ3UJS3QDANCNFSM5FL7NP7Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-10-31 04:15 UTC, davidfarinajr commented
I see, perhaps @mjohnson541 might know what's going on?

2021-10-31 04:23 UTC, mjohnson541 commented
That is certainly a cython error, I'm really not sure what to tell you beyond to run make clean and then make again. Did you do the make clean and make in the rmg_env?

2021-10-31 04:25 UTC, NUSCondy commented
Oh, I forgot to make in rmgenv. Will update it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Matt Johnson ***@***.***>
Sent: Sunday, October 31, 2021 12:23:56 PM
To: ReactionMechanismGenerator/RMG-Py ***@***.***>
Cc: Zhu Qiren ***@***.***>; Mention ***@***.***>
Subject: Re: [ReactionMechanismGenerator/RMG-Py] Fix RMS Object Construction (#2208)

        - External Email -



That is certainly a cython error, I'm really not sure what to tell you beyond to run make clean and then make again. Did you do the make clean and make in the rmg_env?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2208#issuecomment-955634337>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOTBI6RUKFJ2DJZQ3ASMQ5TUJTAFZANCNFSM5FL7NP7Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-11-01 08:37 UTC, NUSCondy commented
Hi,
FYI, the RMG runs normally with both the Aramcomech2.0 and Pdep.