Tweaking Pyjulia and related instructions; make julia system image
ReactionMechanismGenerator/RMG-Py pull request #2443
Opened 2023-05-18 20:12 UTC by rwest

### Motivation or Problem
- We have an old and customized version of pyjulia on the rmg conda channel.
- Time to launch is awful (for me on my mac) because it recompiles a ton of julia stuff every time you import anything from reactors.py
- Some of the code around this was a bit confusing.
- Debugging things with pyjulia involved can be a bit tricky.

### Description of Changes
- switches to the conda-forge version of pyjulia, instead of the customized (and old) rmg channel one, so we are more standardized and have less to maintain.
- incorporates the changes from https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2381  that advises developers to build a system image of julia with RMS compiled.
- adds developer instructions for how to debug (in VSCode)

I am hoping that, before merging, this PR will get this working nicely and greatly accelerate time to launch.

### Testing
It is not yet ready to review for a merge, but I'm opening the pull request now (and requesting reviews)
- to start discussion
- for something for folks to hack on
- to see if it passes the CI tests (including the mac runner)

2023-05-18 22:05 UTC, JacksonBurns requested changes
This will be a nice addition to RMG-Py once it is working - as of writing the conda-forge pyjulia causes build to fail because we have skipped the linking step present in our custom build:

`sed -i 's|bin/python|bin/python3|g' $(which python-jl)`

(from ChatGPT) This command uses the sed command to replace all occurrences of bin/python with bin/python3 in the file specified by $(which python-jl). The -i option modifies the file in place. So, when you run this command, it will replace all instances of bin/python with bin/python3 in the specified file.

I think we can just run this command after solving the conda environment and get the same effect? Or would building the system image remove the need to do so?

I have also left some stylistic comments.

The CI should build a Julia image so that this use case is actually tested, yes?

2023-05-18 22:18 UTC, JacksonBurns commented
Possibly unhelpful idea: [`PythonCall.jl`](https://github.com/cjdoris/PythonCall.jl) is an alternative to PyJulia that is better maintained. They have a page to help [move to their tool](https://cjdoris.github.io/PythonCall.jl/stable/pycall/).
Can we consider doing so?
Would doing so require lots of editing RMS? And potentially also pyrms? Or even RMG's `reactors.py`?
Why do they call it rush hour when nothing moves?

2023-05-19 14:20 UTC, rwest commented on rmgpy/rmg/reactors.py
> +    system_image_path = join(dirname(dirname(dirname(abspath(__file__)))),"rms.so")
I use rmgpy.get_path in  https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2443/commits/841543e867727695eaf3bc5cb98ff0e13fb6f705

Strangely, it's not (for me, yet) much faster. If/when it works well it should absolutely be default.

2023-05-19 14:20 UTC, rwest commented on rmgpy/rmg/reactors.py
> +        "This is the normal case (__debug__ is True by default)"
Done in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2443/commits/5169d108982e378237940a49fe327bfaf536a12b

2023-05-19 14:22 UTC, rwest commented on rmgpy/rmg/reactors.py
Raising an exception to be handled by the calling code would mean the rest of this file would not get imported, which is what this "try/pass" thing is trying to achieve.  I think the use case is code that needs to import this module, but doesn't actually execute anything important in it.
Not very satisfactory, I agree, (in more ways than one) but fixing is beyond scope of this PR.

2023-05-19 14:23 UTC, rwest commented on documentation/source/users/rmg/installation/anacondaDeveloper.rst
> +To build the documentation (to test that you have it right before pushing to Github) you will need to install sphinx::
Fixed in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2443/commits/a358bfa750da9990d9145e8635d029a2bdb33fca

2023-05-19 14:27 UTC, rwest commented on rmgpy/rmg/reactors.py
> +except Exception as e:
I agree in principle, bare exceptions are a code smell. But I'm hoping that in future this whole thing can go away.  I think it was introduced so ARC could pass nose tests or something - where this file is imported somewhere but nothing in it needs to actually run.
For this use case, all exceptions should be treated the same, so I'm going to leave it as is, until we get rid of it entirely.
At least I added some logging so we can see what the exception is.

2023-10-08 08:06 UTC, closed without merging