Added a species constraint for the max number of rings fused together
ReactionMechanismGenerator/RMG-Py pull request #2606
Opened 2024-02-07 12:07 UTC by alongd

### Motivation or Problem
Sometimes users know they are not interested in ring growth in their model, yet RMG spends significant time on suggesting species with complex fused rings. Using the maximum heavy atoms constraints isn't always helpful since other species with the same Mw could be relevant for the model.

### Description of Changes
Added a `maximumFusedRings` key to the constraints dict.
A new method was implemented in Molecule along with a test.

### Testing
A unit test was added.
FWIW, the feature was also tested locally by generating a model that previously gave many fused ring structures and verifying that they are absent now.

### Reviewer Tips
Note that a previously non-implemented constraint was removed from the docs
I saw that this branch fails online due to a Julia installation, I think. Looks unrelated to this feature.

2024-02-08 00:30 UTC, JacksonBurns commented
Blocked by: #2608

2024-02-12 15:03 UTC, JacksonBurns commented
@alongd with the merging of #2608 and #2609 this PR should be good to review after a rebase.

A pre-emptive review comment, though. There are a few mentions of the `maximumIsotopicAtoms` constraint elsewhere in the documentation and examples. See: http://reactionmechanismgenerator.github.io/RMG-Py/search.html?q=maximumIsotopicAtoms+

Could you also remove these? And if there is an associated unit test for `maximumIsotopicAtoms` could you also remove that?

2024-02-26 15:45 UTC, JacksonBurns commented
@alongd the new unit test is failing, see: https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/8028132940/job/21932958791?pr=2606#step:11:1990

It seems like you expect benzene to count as 1 ring in a fused ring system:
```
        mol = Molecule(smiles="c1ccccc1")
        assert mol.get_ring_count_in_largest_fused_ring_system() == 1
```
Should this be so?

2024-02-26 15:45 UTC, JacksonBurns requested changes
See https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2606#issuecomment-1964458524

2024-05-02 08:56 UTC, alongd commented
Sorry for not getting back to this PR, I'm having trouble with Julia and can't run the test locally. I'm getting:

```
Launching pytest with arguments moleculeTest.py::TestMolecule::test_get_ring_count_in_largest_fused_ring_system --no-header --no-summary -q in /home/alon/Code/RMG-Py/test/rmgpy/molecule

DEBUG (1764452) 
DEBUG (1764452) Debug-level logging is enabled for PyJulia.
DEBUG (1764452) PyJulia version: 0.6.1
DEBUG (1764452) pyprogramname = None
DEBUG (1764452) sys.executable = /home/alon/mambaforge/envs/rmg_env/bin/python
DEBUG (1764452) bindir = /home/alon/mambaforge/envs/rmg_env/share/julia/site/julia-1.8.5/bin
DEBUG (1764452) libjulia_path = /home/alon/mambaforge/envs/rmg_env/share/julia/site/julia-1.8.5/bin/../lib/libjulia.so.1

PyCall is not installed or built.  Run the following code in Python REPL:

    >>> import julia
    >>> julia.install()

See:
    https://pyjulia.readthedocs.io/en/latest/installation.html
            
Exit: PyCall not built
!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: PyCall not built !!!!!!!!!!!!!!!!!!!!

Process finished with exit code 1

Empty suite
```

I tried reinstalling Julia and rebuilding as suggested, but still get the same thing

2024-05-03 14:37 UTC, JacksonBurns commented
Hmm that's vexing - could you try installing a more recent version of Julia?

2024-12-05 08:11 UTC, closed without merging