Fix Fragment Resonance Structure Bug
ReactionMechanismGenerator/RMG-Py pull request #2647
Opened 2024-04-02 14:26 UTC by donerancl

### Motivation or Problem
A clear and concise description of what what you're trying to fix or improve. Please reference any issues that this addresses.

### Description of Changes
A clear and concise description of what what you've changed or added.

### Testing
A clear and concise description of testing that you've done or plan to do.

### Reviewer Tips
Suggestions for verifying that this PR works or other notes for the reviewer.

2024-04-02 19:32 UTC, JacksonBurns commented
Hmm so at face value this looks reasonable, and all of the tests pass...

`kekulize` is in two places in RMG, the `molecule.kekulize` method and the `kekulize` function in `kekulize.pyx` - the former simply calls the latter on itself.

I looked around the codebase for other uses of `kekulize` and found this: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/a458b1deb3c26f69cff627396e3a635538c1cff6/rmgpy/data/transport.py#L404

which makes it seem like, in other cases, if kekulization fails we expect it to just throw the error and stop execution.

This `generate_kekule_structure` function is the only place where we actually catch and deal with the error.

Overall I am somewhat unsure if this is an acceptable change.. @hwpang could you take a look at this?

2024-04-02 20:03 UTC, donerancl commented
I think I found the deeper issue. `generate_kekule_structures` loops through atoms and checks for benzene/fused benzene atoms. If it finds one, it immediately tries kekulization. The error arises when `generate_kekule_structures` checks the `atom.atomtype.label` and finds `None`.

2024-04-02 20:25 UTC, donerancl commented
Ok, I fixed the check for `CuttingLabel`s in `generate_kekule_structures`, but any input on whether it is good practice is welcome @JacksonBurns

2024-04-03 18:41 UTC, JacksonBurns requested changes
RMG subgroup discussion - better to directly test if `isinstance(atom, CuttingLabel`. Makes it more obvious what this does.

2024-04-03 19:12 UTC, JacksonBurns commented on rmgpy/molecule/resonance.py
> +        if not isinstance(atom,CuttingLabel):
I think it should be just plain `isinstance` instead of `not isinstance`? i.e. we should skip the atom if it is a cutting label

2024-04-04 14:53 UTC, JacksonBurns commented
This looks good! Could you squash these commits into one (since some of them are just undoing the previous ones) and then re-request a review? Thanks!

2024-04-17 13:53 UTC, JacksonBurns approved these changes
LGTM! Thanks for the patch

2024-04-18 17:32 UTC, merged