Load a kinetic library not in the RMG database
ReactionMechanismGenerator/RMG-Py pull request #2663
Opened 2024-05-18 07:35 UTC by alongd

### Motivation or Problem
Previously a feature (#2340) was added to allow RMG to load external thermo and kinetic libraries. That feature was incomplete, since reaction libraries are stored by their label, and RMG tries to load them by the name provided by the user which is their path.
This issue is not relevant for thermo libraries which are loaded differently in RMG.

### Description of Changes
A dictionary was added to `KineticsDatabase` to map paths to external kinetic libraries with their labels. It is used now in model.py if needed.

### Testing
The feature was tested locally only. Any tips for adding a path (absolute? relative?) to an RMG input file are welcomed to modify [the existing test](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/examples/rmg/external_library/input.py#L9).

### Reviewer Tips
Copy one of the RMG kinetic libraries to a different path and provide the full path in any RMG input file to see that RMG now loads the relevant library correctly.

2024-05-21 20:15 UTC, oscarwumit commented
Thanks for the PR. Overall it looks good. Some minor comments: 
1. Has the new change of including external libraries being documented somewhere? It might be helpful to add some explanations, e.g., what should an user give in "external_library_labels"?
2. Assuming there are kinetic data for the same reaction, both in internal and external libraries, which one takes precedence? e.g., say the same reaction X -> Y appears in internal_lib_1, internal_lib_2, external_lib_A, external_lib_B, which value will be used for simulation in the end?

2024-05-21 20:15 UTC, oscarwumit requested changes

2024-05-25 10:53 UTC, alongd commented on rmgpy/rmg/model.py
> +        elif reaction_library in database.kinetics.external_library_labels.keys():
Yes, it's the same. I prefer the `.keys()` since it's more "formal" or self-explanatory, but I agree it's equivalent

2024-05-25 10:55 UTC, alongd commented
Thanks for the comments, @oscarwumit!
I added the documentation as requested, definitely a good idea. The regression tests are failing, but with minimal differences not due to this PR, I think it's safe to merge.

2024-05-28 16:22 UTC, JacksonBurns commented on rmgpy/rmg/model.py
> +        elif reaction_library in database.kinetics.external_library_labels.keys():
I prefer the explicit version alon has as well!

2024-05-28 16:23 UTC, JacksonBurns submitted a review, later dismissed
I concur with @oscarwumit about the docs changes, this looks good once the CI goes through

2024-05-31 02:08 UTC, alongd commented
@JacksonBurns, the regression tests still fail, as discussed. Is it OK to merge despite this, or is there a solution coming along to this issue?

2024-05-31 16:42 UTC, JacksonBurns commented
@alongd I should clarify, when I say that it is ok if the regression tests 'fail', I mean that they should still _execute_, but that it will put some output on the PR about how species are different, like in this PR: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2646#issuecomment-2032883276

The actual continuous integration action won't complete it's execution in this PR. I don't know why, and it seems like the failures are spurious (network problems, etc). I have re-run a third time now, hoping that the inconsistency will resolve itself.

2024-06-04 17:37 UTC, JacksonBurns commented
I have _no idea_ why the regression tests aren't executing... @rwest could you take a look at this? The 'raw logs' are empty, steps are being skipped for now apparent reason, I am lost. I will open another PR making a whitespace change to see if the CI is actually broken, but otherwise I have no idea.

My only guess would be that something in this change is so catastrophic that the regression difference files are crashing the runner (?). We saw something similar in the past where there were so may changes we had to add an alternative to writing all of them.

2024-06-04 19:17 UTC, rwest commented
Are we looking at https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/9234927578/job/25784303822?pr=2663 ? the fact that it failed after 199 minutes and 55 seconds for no obvious reason makes me suspicious there's a 200 minute limit?

2024-06-05 19:05 UTC, JacksonBurns commented
That's a coincidence, the actual limit is 6 hours: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

2024-06-07 15:55 UTC, JacksonBurns commented
I missed this comment yesterday, but I ended up going with the latter

2024-06-11 20:52 UTC, JacksonBurns commented
@oscarwumit CI is fixed, could you re-review? Thanks

2024-06-12 04:21 UTC, oscarwumit reviewed
Only a minor comment. Can be merged after fixed.

2024-06-12 04:21 UTC, oscarwumit commented on rmgpy/rmg/model.py
> +        elif reaction_library in database.kinetics.external_library_labels.keys():
I am fine with either option. Then I think line 1721 should be consistent with line 1723.
i.e., if reaction_library in database.kinetics.libraries**.keys()**:

2024-06-13 09:06 UTC, alongd commented
@oscarwumit, Thanks for the comments, I made the code consistent now as requested (also, thanks for @rwest's comment)
Oscar, I added [another small commit](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2663/commits/b9a9c0d469eb20f8b75ea269aa3caa4ccb9a005f) to process kinetics library paths that users give which end with a `/`.
If all looks fine, we can merge. Thanks!

2024-06-18 09:06 UTC, oscarwumit approved these changes
Looks good to me. Thanks.

2024-06-18 13:10 UTC, JacksonBurns approved these changes

2024-06-18 13:10 UTC, merged